CREATE TABLE TAX (
  ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
  LABEL  VARCHAR(1) NOT NULL,
  VALUE DECIMAL(10,2) NOT NULL
);

INSERT INTO TAX(LABEL, VALUE) VALUES ('A', 0);
INSERT INTO TAX(LABEL, VALUE) VALUES ('B', 10);
INSERT INTO TAX(LABEL, VALUE) VALUES ('C', 20);

CREATE TABLE RISK (
  ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
  CLIENT_NAME  VARCHAR(100) NOT NULL,
  LIMIT_VALUE  DECIMAL(19, 2) NOT NULL,
  TOTAL_VALUE  DECIMAL(19, 2) NOT NULL,
  TAX_ID BIGINT NOT NULL,
  CREATED_TIME TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

 ALTER TABLE RISK ADD CONSTRAINT FK_TAX_ID FOREIGN KEY (TAX_ID) REFERENCES TAX (ID);